[workspace.package]
description = "Converts Nix-tracing tool output into CycloneDX"
version = "0.1.0"
edition = "2021"
authors = ["Tweag I/O"]
license = "MIT"
repository = "https://github.com/Tweag/genealogos"
keywords = ["nix", "cyclonedx", "conversion"]
readme = "README.md"

[workspace]
members = ["genealogos", "genealogos-cli", "genealogos-api"]
resolver = "2"

[workspace.dependencies]
chrono = "0.4.34"
clap = { version = "4.4.14", features = ["derive"] }
log = "0.4"
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-cyclonedx = "0.8"
thiserror = "1.0"
uuid = { version = "1.6", features = ["v4"] }

env_logger = "0.10"
predicates = "3.1"
pretty_assertions = "1.4"
test-log = "0.2"
urlencoding = "2.1"
