[package]
name = "genealogos"
version = "0.1.0"
edition = "2021"
authors = ["Tweag I/O"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde-cyclonedx = "0.8"
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4"] }
