name: "Verify the conformity of output files"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - name: Verifying output files
        run: nix run .#verify-fixture-files --extra-experimental-features 'nix-command flakes'
