name: "Verify the conformity of output files"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - name: Verifying output files
        run: |
          for f in ./genealogos/tests/fixtures/nixtract/success/*.out; do
            OUT=$(nix run .#cyclonedx --extra-experimental-features 'nix-command flakes' -- validate --input-format json --input-version v1_5 --input-file "$f")
            # Fail if the cyclonedx tool did not output a message containing "successfully"
            [[ "$OUT" =~ .*successfully.* ]] || exit 1
          done || exit 1
